//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 4/7/2016 12:39:38 PM
namespace EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models
{
    /// <summary>
    /// There are no comments for ContactSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ContactSingle")]
    public partial class ContactSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Contact>
    {
        /// <summary>
        /// Initialize a new ContactSingle object.
        /// </summary>
        public ContactSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ContactSingle object.
        /// </summary>
        public ContactSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ContactSingle object.
        /// </summary>
        public ContactSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Contact> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Department in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Department")]
        public global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DepartmentSingle Department
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Department == null))
                {
                    this._Department = new global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DepartmentSingle(this.Context, GetPath("Department"));
                }
                return this._Department;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DepartmentSingle _Department;
        /// <summary>
        /// There are no comments for ContactTasks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ContactTasks")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTask> ContactTasks
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ContactTasks == null))
                {
                    this._ContactTasks = Context.CreateQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTask>(GetPath("ContactTasks"));
                }
                return this._ContactTasks;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTask> _ContactTasks;
    }
    /// <summary>
    /// There are no comments for Contact in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Contact")]
    public partial class Contact : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Contact object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Contact CreateContact(int ID)
        {
            Contact contact = new Contact();
            contact.Id = ID;
            return contact;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Address")]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this._Address = value;
                this.OnAddressChanged();
                this.OnPropertyChanged("Address");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property Department in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Department")]
        public global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Department Department
        {
            get
            {
                return this._Department;
            }
            set
            {
                this.OnDepartmentChanging(value);
                this._Department = value;
                this.OnDepartmentChanged();
                this.OnPropertyChanged("Department");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Department _Department;
        partial void OnDepartmentChanging(global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Department value);
        partial void OnDepartmentChanged();
        /// <summary>
        /// There are no comments for Property ContactTasks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ContactTasks")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTask> ContactTasks
        {
            get
            {
                return this._ContactTasks;
            }
            set
            {
                this.OnContactTasksChanging(value);
                this._ContactTasks = value;
                this.OnContactTasksChanged();
                this.OnPropertyChanged("ContactTasks");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTask> _ContactTasks = new global::Microsoft.OData.Client.DataServiceCollection<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTask>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnContactTasksChanging(global::Microsoft.OData.Client.DataServiceCollection<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTask> value);
        partial void OnContactTasksChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DemoTaskSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DemoTaskSingle")]
    public partial class DemoTaskSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<DemoTask>
    {
        /// <summary>
        /// Initialize a new DemoTaskSingle object.
        /// </summary>
        public DemoTaskSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new DemoTaskSingle object.
        /// </summary>
        public DemoTaskSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new DemoTaskSingle object.
        /// </summary>
        public DemoTaskSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<DemoTask> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for ContactTasks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ContactTasks")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTask> ContactTasks
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ContactTasks == null))
                {
                    this._ContactTasks = Context.CreateQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTask>(GetPath("ContactTasks"));
                }
                return this._ContactTasks;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTask> _ContactTasks;
    }
    /// <summary>
    /// There are no comments for DemoTask in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("DemoTask")]
    public partial class DemoTask : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DemoTask object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="startDate">Initial value of StartDate.</param>
        /// <param name="dateCompleted">Initial value of DateCompleted.</param>
        /// <param name="percentCompleted">Initial value of PercentCompleted.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static DemoTask CreateDemoTask(int ID, global::System.DateTimeOffset startDate, global::System.DateTimeOffset dateCompleted, int percentCompleted)
        {
            DemoTask demoTask = new DemoTask();
            demoTask.Id = ID;
            demoTask.StartDate = startDate;
            demoTask.DateCompleted = dateCompleted;
            demoTask.PercentCompleted = percentCompleted;
            return demoTask;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Description")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Note in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Note")]
        public string Note
        {
            get
            {
                return this._Note;
            }
            set
            {
                this.OnNoteChanging(value);
                this._Note = value;
                this.OnNoteChanged();
                this.OnPropertyChanged("Note");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Note;
        partial void OnNoteChanging(string value);
        partial void OnNoteChanged();
        /// <summary>
        /// There are no comments for Property StartDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("StartDate")]
        public global::System.DateTimeOffset StartDate
        {
            get
            {
                return this._StartDate;
            }
            set
            {
                this.OnStartDateChanging(value);
                this._StartDate = value;
                this.OnStartDateChanged();
                this.OnPropertyChanged("StartDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _StartDate;
        partial void OnStartDateChanging(global::System.DateTimeOffset value);
        partial void OnStartDateChanged();
        /// <summary>
        /// There are no comments for Property DateCompleted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DateCompleted")]
        public global::System.DateTimeOffset DateCompleted
        {
            get
            {
                return this._DateCompleted;
            }
            set
            {
                this.OnDateCompletedChanging(value);
                this._DateCompleted = value;
                this.OnDateCompletedChanged();
                this.OnPropertyChanged("DateCompleted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _DateCompleted;
        partial void OnDateCompletedChanging(global::System.DateTimeOffset value);
        partial void OnDateCompletedChanged();
        /// <summary>
        /// There are no comments for Property PercentCompleted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PercentCompleted")]
        public int PercentCompleted
        {
            get
            {
                return this._PercentCompleted;
            }
            set
            {
                this.OnPercentCompletedChanging(value);
                this._PercentCompleted = value;
                this.OnPercentCompletedChanged();
                this.OnPropertyChanged("PercentCompleted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _PercentCompleted;
        partial void OnPercentCompletedChanging(int value);
        partial void OnPercentCompletedChanged();
        /// <summary>
        /// There are no comments for Property ContactTasks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ContactTasks")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTask> ContactTasks
        {
            get
            {
                return this._ContactTasks;
            }
            set
            {
                this.OnContactTasksChanging(value);
                this._ContactTasks = value;
                this.OnContactTasksChanged();
                this.OnPropertyChanged("ContactTasks");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTask> _ContactTasks = new global::Microsoft.OData.Client.DataServiceCollection<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTask>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnContactTasksChanging(global::Microsoft.OData.Client.DataServiceCollection<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTask> value);
        partial void OnContactTasksChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ContactTaskSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ContactTaskSingle")]
    public partial class ContactTaskSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<ContactTask>
    {
        /// <summary>
        /// Initialize a new ContactTaskSingle object.
        /// </summary>
        public ContactTaskSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ContactTaskSingle object.
        /// </summary>
        public ContactTaskSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ContactTaskSingle object.
        /// </summary>
        public ContactTaskSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<ContactTask> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Contact in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Contact")]
        public global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactSingle Contact
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Contact == null))
                {
                    this._Contact = new global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactSingle(this.Context, GetPath("Contact"));
                }
                return this._Contact;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactSingle _Contact;
        /// <summary>
        /// There are no comments for Task in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Task")]
        public global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DemoTaskSingle Task
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Task == null))
                {
                    this._Task = new global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DemoTaskSingle(this.Context, GetPath("Task"));
                }
                return this._Task;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DemoTaskSingle _Task;
    }
    /// <summary>
    /// There are no comments for ContactTask in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("ContactTask")]
    public partial class ContactTask : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ContactTask object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="taskId">Initial value of TaskId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static ContactTask CreateContactTask(int ID, int taskId)
        {
            ContactTask contactTask = new ContactTask();
            contactTask.Id = ID;
            contactTask.TaskId = taskId;
            return contactTask;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property ContactId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ContactId")]
        public global::System.Nullable<int> ContactId
        {
            get
            {
                return this._ContactId;
            }
            set
            {
                this.OnContactIdChanging(value);
                this._ContactId = value;
                this.OnContactIdChanged();
                this.OnPropertyChanged("ContactId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _ContactId;
        partial void OnContactIdChanging(global::System.Nullable<int> value);
        partial void OnContactIdChanged();
        /// <summary>
        /// There are no comments for Property TaskId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TaskId")]
        public int TaskId
        {
            get
            {
                return this._TaskId;
            }
            set
            {
                this.OnTaskIdChanging(value);
                this._TaskId = value;
                this.OnTaskIdChanged();
                this.OnPropertyChanged("TaskId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _TaskId;
        partial void OnTaskIdChanging(int value);
        partial void OnTaskIdChanged();
        /// <summary>
        /// There are no comments for Property Contact in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Contact")]
        public global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Contact Contact
        {
            get
            {
                return this._Contact;
            }
            set
            {
                this.OnContactChanging(value);
                this._Contact = value;
                this.OnContactChanged();
                this.OnPropertyChanged("Contact");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Contact _Contact;
        partial void OnContactChanging(global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Contact value);
        partial void OnContactChanged();
        /// <summary>
        /// There are no comments for Property Task in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Task")]
        public global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DemoTask Task
        {
            get
            {
                return this._Task;
            }
            set
            {
                this.OnTaskChanging(value);
                this._Task = value;
                this.OnTaskChanged();
                this.OnPropertyChanged("Task");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DemoTask _Task;
        partial void OnTaskChanging(global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DemoTask value);
        partial void OnTaskChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DepartmentSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DepartmentSingle")]
    public partial class DepartmentSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Department>
    {
        /// <summary>
        /// Initialize a new DepartmentSingle object.
        /// </summary>
        public DepartmentSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new DepartmentSingle object.
        /// </summary>
        public DepartmentSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new DepartmentSingle object.
        /// </summary>
        public DepartmentSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Department> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Contacts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Contacts")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Contact> Contacts
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Contacts == null))
                {
                    this._Contacts = Context.CreateQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Contact>(GetPath("Contacts"));
                }
                return this._Contacts;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Contact> _Contacts;
    }
    /// <summary>
    /// There are no comments for Department in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Department")]
    public partial class Department : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Department object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Department CreateDepartment(int ID)
        {
            Department department = new Department();
            department.Id = ID;
            return department;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Title")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Office in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Office")]
        public string Office
        {
            get
            {
                return this._Office;
            }
            set
            {
                this.OnOfficeChanging(value);
                this._Office = value;
                this.OnOfficeChanged();
                this.OnPropertyChanged("Office");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Office;
        partial void OnOfficeChanging(string value);
        partial void OnOfficeChanged();
        /// <summary>
        /// There are no comments for Property Contacts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Contacts")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Contact> Contacts
        {
            get
            {
                return this._Contacts;
            }
            set
            {
                this.OnContactsChanging(value);
                this._Contacts = value;
                this.OnContactsChanged();
                this.OnPropertyChanged("Contacts");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Contact> _Contacts = new global::Microsoft.OData.Client.DataServiceCollection<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Contact>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnContactsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Contact> value);
        partial void OnContactsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Contact as global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Contact> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Contact as global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Contact> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DemoTask as global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DemoTaskSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DemoTaskSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DemoTask> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DemoTaskSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DemoTask as global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DemoTaskSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DemoTaskSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DemoTask> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DemoTaskSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTask as global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTaskSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTaskSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTask> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTaskSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTask as global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTaskSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTaskSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTask> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTaskSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Department as global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DepartmentSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DepartmentSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Department> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DepartmentSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Department as global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DepartmentSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DepartmentSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Department> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DepartmentSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace EFCoreSecurityConsoleClient.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "EFCoreSecurityODataService.Models", "EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "EFCoreSecurityConsoleClient.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("EFCoreSecurityODataService.Models.", originalNameAttribute.OriginalName);
                }
                return string.Concat("EFCoreSecurityODataService.Models.", clientType.Name);
            }
            if (clientType.Namespace.Equals("EFCoreSecurityConsoleClient.Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Contacts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Contacts")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Contact> Contacts
        {
            get
            {
                if ((this._Contacts == null))
                {
                    this._Contacts = base.CreateQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Contact>("Contacts");
                }
                return this._Contacts;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Contact> _Contacts;
        /// <summary>
        /// There are no comments for Tasks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Tasks")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DemoTask> Tasks
        {
            get
            {
                if ((this._Tasks == null))
                {
                    this._Tasks = base.CreateQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DemoTask>("Tasks");
                }
                return this._Tasks;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DemoTask> _Tasks;
        /// <summary>
        /// There are no comments for ContactTasks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ContactTasks")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTask> ContactTasks
        {
            get
            {
                if ((this._ContactTasks == null))
                {
                    this._ContactTasks = base.CreateQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTask>("ContactTasks");
                }
                return this._ContactTasks;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTask> _ContactTasks;
        /// <summary>
        /// There are no comments for Departments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Departments")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Department> Departments
        {
            get
            {
                if ((this._Departments == null))
                {
                    this._Departments = base.CreateQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Department>("Departments");
                }
                return this._Departments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Department> _Departments;
        /// <summary>
        /// There are no comments for Contacts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToContacts(global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Contact contact)
        {
            base.AddObject("Contacts", contact);
        }
        /// <summary>
        /// There are no comments for Tasks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToTasks(global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.DemoTask demoTask)
        {
            base.AddObject("Tasks", demoTask);
        }
        /// <summary>
        /// There are no comments for ContactTasks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToContactTasks(global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.ContactTask contactTask)
        {
            base.AddObject("ContactTasks", contactTask);
        }
        /// <summary>
        /// There are no comments for Departments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToDepartments(global::EFCoreSecurityConsoleClient.EFCoreSecurityODataService.Models.Department department)
        {
            base.AddObject("Departments", department);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""EFCoreSecurityODataService.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Contact"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""Address"" Type=""Edm.String"" />
        <NavigationProperty Name=""Department"" Type=""EFCoreSecurityODataService.Models.Department"" />
        <NavigationProperty Name=""ContactTasks"" Type=""Collection(EFCoreSecurityODataService.Models.ContactTask)"" />
      </EntityType>
      <EntityType Name=""DemoTask"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Description"" Type=""Edm.String"" />
        <Property Name=""Note"" Type=""Edm.String"" />
        <Property Name=""StartDate"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""DateCompleted"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""PercentCompleted"" Type=""Edm.Int32"" Nullable=""false"" />
        <NavigationProperty Name=""ContactTasks"" Type=""Collection(EFCoreSecurityODataService.Models.ContactTask)"" />
      </EntityType>
      <EntityType Name=""ContactTask"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""ContactId"" Type=""Edm.Int32"" />
        <Property Name=""TaskId"" Type=""Edm.Int32"" Nullable=""false"" />
        <NavigationProperty Name=""Contact"" Type=""EFCoreSecurityODataService.Models.Contact"">
          <ReferentialConstraint Property=""ContactId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
        <NavigationProperty Name=""Task"" Type=""EFCoreSecurityODataService.Models.DemoTask"" />
      </EntityType>
      <EntityType Name=""Department"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Title"" Type=""Edm.String"" />
        <Property Name=""Office"" Type=""Edm.String"" />
        <NavigationProperty Name=""Contacts"" Type=""Collection(EFCoreSecurityODataService.Models.Contact)"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Contacts"" EntityType=""EFCoreSecurityODataService.Models.Contact"">
          <NavigationPropertyBinding Path=""Department"" Target=""Departments"" />
          <NavigationPropertyBinding Path=""ContactTasks"" Target=""ContactTasks"" />
        </EntitySet>
        <EntitySet Name=""Tasks"" EntityType=""EFCoreSecurityODataService.Models.DemoTask"">
          <NavigationPropertyBinding Path=""ContactTasks"" Target=""ContactTasks"" />
        </EntitySet>
        <EntitySet Name=""ContactTasks"" EntityType=""EFCoreSecurityODataService.Models.ContactTask"">
          <NavigationPropertyBinding Path=""Contact"" Target=""Contacts"" />
          <NavigationPropertyBinding Path=""Task"" Target=""Tasks"" />
        </EntitySet>
        <EntitySet Name=""Departments"" EntityType=""EFCoreSecurityODataService.Models.Department"">
          <NavigationPropertyBinding Path=""Contacts"" Target=""Contacts"" />
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
